#Calcular el área de un círculo, dado su radio
#import math #para importar la biblioteca math
#r = int(input("Ingrese el radio: ")) #creo variable r y le pido al usuario que ingrese el radio. lo convierto a numero
#print("El área del círculo es de " + str(math.pi * r**2)) #uso la funcion pi de la biblioteca math. convierto el area a texto
#Ingresar numero entero y calcular n + nn + nnn
#numero = int(input("Ingrese un número: "))
#print(numero + numero**2 + numero**3)
#programa que cuente cadena de caracteres y cuente el tamaño y cuantas veces aparece la letra a, tanto mayus como min
#hora actual pero sumar dos horas adicionales
import datetime
futurahora=int(datetime.time())
futurahora=futurahora + 2
print(futurahora)